config/routes.rb
MovieNight::Application.routes.draw do
  get '/signout' => 'sessions#destroy', as: :signout
  get '/signet/google/auth_callback' => 'sessions#create'

  root to: 'home#index'

  resources :movies, except: [:edit, :update, :destroy]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    home_abilites

    unless user.nil?
      movie_abilities
    end
  end

private

  def home_abilites
    can :index, :home
  end

  def movie_abilities
    can [:index, :new, :create], Movie
  end

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  belongs_to :user

  serialize :genres, Array

  validates :title, presence: :true, if: ->(m){ m.current_step == 'set_title' }
  validates :imdb_id, presence: true, if: ->(m){ m.current_step == 'choose_from_imdb' }
  validates :imdb_id, uniqueness: true, if: ->(m){ m.imdb_id.present? }

  before_save :get_data_from_imdb, if: ->(m){ m.title.nil? }

  attr_writer :current_step

  def current_step
    @current_step || steps.first
  end

  def steps
    %w[set_title choose_from_imdb]
  end

  def next_step
    self.current_step = steps[steps.index(current_step)+1] unless last_step?
  end

  def previous_step
    self.current_step = steps[steps.index(current_step)-1] unless first_step?
  end

  def first_step?
    current_step == steps.first
  end

  def last_step?
    current_step == steps.last
  end

private

  def get_data_from_imdb
    imdb_movie = IMDB.find_movie_by_id(self.imdb_id)
    data       = imdb_movie_to_attributes(imdb_movie)
    assign_attributes(data)
  end

  def imdb_movie_to_attributes(imdb_movie)
    {
      title:        imdb_movie.title,
      tagline:      imdb_movie.tagline,
      plot:         imdb_movie.plot,
      genres:       imdb_movie.genres,
      poster_url:   imdb_movie.poster_url,
      trailer_url:  imdb_movie.trailers.try(:first).try(:last),
      year:         imdb_movie.release_date.try(:to_date).try(:year),
    }
  end

end

app/models/o_auth2_credential.rb
class OAuth2Credential < ActiveRecord::Base
  belongs_to :user
  serialize :signet, Hash
  validates_uniqueness_of :name, scope: :id
end

app/models/user.rb
class User < ActiveRecord::Base
   has_many :o_auth2_credentials, dependent: :destroy
   has_many :movies, dependent: :destroy

   validates :uid, presence: true
   validates :email, uniqueness: { case_sensitive: false }, if: ->(u){ u.email.present? }

   def full_name
    "#{name} #{surname}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?
  before_filter :reset_session
  before_filter :prepare_resource, only: [:create]
  check_authorization

  def current_user
    u = nil
    if !!session[:user_id]
      begin
        u = User.find(session[:user_id])
      rescue ActiveRecord::RecordNotFound => e
        session[:user_id] = nil
      end
    end
    u
  end

  def logged_in?
    !!current_user
  end

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end

private

  def reset_session
    session[:movie_step] = nil
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    authorize! :index, :home
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  load_and_authorize_resource
  skip_before_filter :reset_session, only: [:create]

  def index
  end

  def new
  end

  def create
    @movie.current_step = session[:movie_step]

    save_or_next_step
    redirect_or_render
  end

private

  def movie_params
    params.require(:movie).permit(:title, :imdb_id)
  end

  def save_or_next_step
    if @movie.valid?
      if @movie.last_step?
        @movie.user = current_user
        @movie.save
      else
        session[:movie_step] = @movie.next_step
      end
    end
  end

  def redirect_or_render
    if @movie.new_record?
      @movies = IMDB.find_by_title(@movie.title) if @movie.current_step == 'choose_from_imdb'
      render :new
    else
      session[:movie_step] = nil
      redirect_to action: :index
    end
  end

  def prepare_resource
    @movie = Movie.new movie_params
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_authorization_check
  skip_before_filter :prepare_resource

  def create
    user = request.env['signet.google.persistence_obj'].user
    session[:user_id] = user.id
    flash[:notice] = 'Signed In!'

    update_user_data(user)
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'Signed Out'
    redirect_to root_url
  end

private

  def update_user_data(user)
    data = get_user_data
    user.update_attributes  email: data['email'],
                            name: data['given_name'],
                            surname: data['family_name'],
                            avatar: data['picture']
  end

  def get_user_data
    auth = Signet::Rails::Factory.create_from_env :google, request.env
    client = Google::APIClient.new
    client.authorization = auth
    service = client.discovered_api('oauth2', 'v2')
    result = client.execute(
      :api_method => service.userinfo.v2.me.get,
      :parameters => {},
      :headers => {'Content-Type' => 'application/json'}
    )
    JSON.parse(result.body)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
  def imdb_link_for(imdb_id)
    "http://www.imdb.com/title/#{imdb_id}/"
  end
end

app/views/home/_logged_in.html.haml
%h1= "Welcome to movie nights #{current_user.full_name}!"

%h3
  Your movie propositions

= render partial: "/movies/table", locals: { movies: current_user.movies }

app/views/home/_not_logged_in.html.haml
.jumbotron
  %h1
    Welcome to movie night app!

  = link_to "Login to continue", '/signet/google/auth', class: "btn btn-default"

app/views/home/index.html.haml
.container
  - if logged_in?
    = render "logged_in"
  - else
    = render "not_logged_in"

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "danger"}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

      .navbar-right
        - if logged_in?
          .navbar-text
            = current_user.full_name
          = image_tag current_user.avatar, class: ["img-circle", "navbar-image"]
          = link_to 'Sign out', signout_path, class: ["btn btn-default", "navbar-btn"]
        - else
          = link_to '/signet/google/auth', class: ["btn btn-default", "navbar-btn"] do
            = image_tag 'google_21.png'

app/views/layouts/_navigation_links.html.haml
- if can?(:index, Movie)
  %li= link_to"Movies", movies_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Movie Night'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Movie Night'}"}
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/movies/_choose_from_imdb_step.html.haml
%table.table.table-striped#imdb-suggestions
  %thead
    %tr
      %th= "Title"
      %th= "Year"
      %th

  %tbody
    - @movies.each do |movie|
      %tr{ id: movie[:imdb_id] }
        %td= movie[:title]
        %td= movie[:year][0]
        %td
          = simple_form_for @movie, role: "form", class: "form-horizontal" do |f|
            = f.input :imdb_id, as: :hidden, input_html: { value: movie[:imdb_id] }
            = link_to imdb_link_for(movie[:imdb_id]), class: ["btn", "btn-default", "btn-sm"], target: "_blank" do
              IMDB
              %i.fa.fa-external-link
            = f.button :button, type: :submit, class: ["btn", "btn-sm", "btn-primary"] do
              Add
              %i.fa.fa-plus

app/views/movies/_info.html.haml
.modal.fade{ id: "movie-info-#{movie.id}", tabindex: "-1", role: "dialog", aria: { labelledby: "#{movie.title}", hidden: "true" }}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{ type: "button", data: { dismiss: "modal" }, aria: { hidden: "true" }}
          &times
        %h4.modal-title{ id: "#{movie.title}" }
          = "#{movie.title} info"
      .modal-body
        %ul.nav.nav-tabs.nav-justified
          %li.active=link_to 'Info', "#movie-#{movie.id}-info", data: { toggle: "tab" }
          %li= link_to 'Trailer', "#movie-#{movie.id}-trailer", data: { toggle: "tab" }

        .tab-content
          .tab-pane.active{ id: "movie-#{movie.id}-info" }
            .row
              .col-md-4
                = image_tag movie.poster_url, class: "poster"
              .col-md-8
                .row
                  .col-md-2
                    %strong= "Title:"
                  .col-md-10= movie.title

                .row
                  .col-md-2
                    %strong= "Year:"
                  .col-md-10= movie.year

                .row
                  .col-md-2
                    %strong= "Tagline:"
                  .col-md-10= movie.tagline

                .row
                  .col-md-2
                    %strong= "Plot:"
                  .col-md-10= movie.plot

                .row
                  .col-md-2
                    %strong= "Genres:"
                  .col-md-10= movie.genres.join(", ")

          .tab-pane{ id: "movie-#{movie.id}-trailer" }
            .text-center
              %video.trailer{ controls: true }
                %source{ src: movie.trailer_url }

      .modal-footer
        %button.btn.btn-default{ type: "button", data: { dismiss: "modal" }}
          OK

app/views/movies/_row.html.haml
= render partial: "/movies/info", locals: {movie: movie}

%tr{id: "movie-#{movie.id}"}
  %td
    %div= movie.title
    %small= movie.tagline
  %td= movie.year
  %td
    - if movie.user.present?
      .pull-left.margin-right= movie.user.full_name
      .pull-left= image_tag movie.user.avatar, class: ["img-circle"], size: "25x25"

  %td
    = link_to imdb_link_for(movie.imdb_id), class: ["btn", "btn-default", "btn-sm"], target: "_blank" do
      IMDB
      %i.fa.fa-external-link
    = link_to "#movie-info-#{movie.id}", class: ["btn", "btn-primary" ,"btn-sm"], data: { toggle: "modal" } do
      More
      %i.fa.fa-toggle-up

app/views/movies/_set_title_step.html.haml
= simple_form_for @movie, role: "form", html: {class: "form-horizontal"}, defaults: {label_html: {class: ["control-label", "col-sm-2"]}, input_html: {class: ["form-control"]}} do |f|
  .form-group
    = f.input :title
  .form-group
    .col-sm-2.col-sm-offset-10
      = f.button :button, type: :submit, class: ["btn", "btn-primary"] do
        = "Continue"
        %i.fa.fa-caret-right

app/views/movies/_table.html.haml
.pull-right
  = link_to new_movie_path, class: ["btn", "btn-primary"] do
    Add movie
    %i.fa.fa-plus

.table-responsive
  %table.table.table-striped.table-hover.movies
    %thead
      %tr
        %th= "Title"
        %th= "Year"
        %th= "Proposed by"
        %th

    %tbody
      = render partial: "/movies/row", collection: movies, as: :movie

app/views/movies/index.html.haml
.container
  %h1
    Movies

  = render partial: "table", locals: { movies: @movies }

app/views/movies/new.html.haml
.container
  %h2= "Add movie"

  = render "#{@movie.current_step}_step"